# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('detail', models.TextField()),
                ('done', models.BooleanField()),
                ('dead_line', models.DateTimeField()),
            ],
        ),
    ]
