# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='dead_line',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
